DESCRIPTION LATER ON!

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import time

In [19]:
#creating arrays with numpy
a = np.zeros(4)
print(f"a = np.zeros(4): {a}, a.shape: {a.shape}, a data type: {a.dtype}")
a = np.zeros((4,))
print(f"a = np.zeros((4,)): {a}, a.shape: {a.shape}, a data type: {a.dtype}")

a = np.zeros(4): [0. 0. 0. 0.], a.shape: (4,), a data type: float64
a = np.zeros((4,)): [0. 0. 0. 0.], a.shape: (4,), a data type: float64


In [6]:
#creating 1D array with random values
a = np.random.random_sample(4)
print(f"a with random values: {a}, a.shape: {a.shape}, a data type: {a.dtype}")

a with random values: [0.13680701 0.67266195 0.73827361 0.18462016], a.shape: (4,), a data type: float64


In [22]:
a.shape[0]

4

In [13]:
#some data creation routines do not take tuples
a = np.random.rand(4)
print(f"random.rand a : {a}, a.shape: {a.shape}, a.dtype: {a.dtype}")
a = np.arange(4)
print(f"arange a: {a}, a.shape: {a.shape}, a.dtype: {a.dtype}")

random.rand a : [0.82678191 0.95455564 0.88293828 0.53000777], a.shape: (4,), a.dtype: float64
arange a: [0 1 2 3], a.shape: (4,), a.dtype: int32


In [15]:
a = np.random.random_sample((3,5))
a

array([[0.80222726, 0.1248089 , 0.77339545, 0.98631312, 0.94934504],
       [0.27645572, 0.57555558, 0.84087774, 0.32464005, 0.2226991 ],
       [0.45420501, 0.51864012, 0.6522151 , 0.55264413, 0.165612  ]])

In [18]:
a = np.random.rand(3,5)
a

array([[0.09837877, 0.85459177, 0.77010263, 0.89984434, 0.04968621],
       [0.13946945, 0.39708418, 0.26231707, 0.8592016 , 0.71555755],
       [0.98998484, 0.03403305, 0.82824581, 0.16516555, 0.05226473]])

In [23]:
def dot_product(a, b):
    """
    Objective- find the dot product of the 2 1-D vectors a and b
    Returns: scalar value of the product.
    """
    n = a.shape[0]
    prod = 0.0
    for i in range(n):
        prod = prod + a[i]*b[i]
    return prod

In [24]:
a = np.random.rand(3)
b = np.random.rand(3)
print(f"a: {a}\nb: {b}")

a: [0.20277486 0.24350714 0.38226407]
b: [0.89941738 0.01890982 0.98821739]


In [29]:
print(round(dot_product(a,b),4))

0.5647


In [34]:
#Checking the speed of our created function and numpy dot product

#create large arrays
a = np.random.rand(10000000)
b = np.random.rand(10000000)
initial_time = time.time()
prod1 = dot_product(a,b)
final_time = time.time()
print(f"Initial time: {initial_time}\nFinal time: {final_time}\nTime taken: {(final_time - initial_time)*1000} milliseconds")

Initial time: 1686307433.6592886
Final time: 1686307438.3383396
Time taken: 4679.050922393799 milliseconds


In [35]:
#repeat same process, now using numpy dot product
i_time = time.time()
prod2 = np.dot(a,b)
f_time = time.time()
print(f"Time taken using Numpy dot product: {(f_time - i_time)*1000} milliseconds")

Time taken using Numpy dot product: 16.017913818359375 milliseconds


In [36]:
#remove these big arrays from memory
del(a)
del(b)

In [44]:
#reshape() is a convinient method to create matrices in numpy
#-1 signifies unknown dimension.
arr1 = np.arange(12).reshape(-1,3)
print(arr1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [48]:
#accessing elements of matrix by specifying only row number
arr1[3].shape

(3,)

In [57]:
#slicing & indexing through the matrix
arr1[1:-1]

array([[3, 4, 5],
       [6, 7, 8]])

In [64]:
#return all elements of 1st row
print(f"All elements of row 1 of arr1 = arr1[1,:]: {arr1[1,:]}")
#return the first row
print(f"1st row of arr1 = arr1[1]: {arr1[1]}")
#return 2nd and 3rd values from 1st row
print(f"2nd and 3rd element of row 1 = arr1[1,1:3]: {arr1[1,1:3]}")
#return 1st and 2nd values from 1st row
print(f"1st and 2nd element of row 1 = arr1[1,0:2]: {arr1[1,0:2]}")

All elements of row 1 of arr1 = arr1[1,:]: [3 4 5]
1st row of arr1 = arr1[1]: [3 4 5]
2nd and 3rd element of row 1 = arr1[1,1:3]: [4 5]
1st and 2nd element of row 1 = arr1[1,0:2]: [3 4]
